CREATE TABLE IF NOT EXISTS `subarea_data` (
  `ID` smallint(4) NOT NULL,
  `Area` smallint(3) NOT NULL,
  `Alignment_Side` int(11) NOT NULL DEFAULT '-1',
  `Name` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `subarea_data` VALUES ('0', '0', '-1', 'Amakna');
INSERT INTO `subarea_data` VALUES ('1', '0', '-1', 'Port de Madrestam');
INSERT INTO `subarea_data` VALUES ('2', '0', '-1', 'La montagne des Craqueleurs');
INSERT INTO `subarea_data` VALUES ('3', '0', '-1', 'Le champ des Ingalsses');
INSERT INTO `subarea_data` VALUES ('4', '0', '-1', 'La foret d\'Amakna');
INSERT INTO `subarea_data` VALUES ('5', '0', '-1', 'Le coin des Bouftous');
INSERT INTO `subarea_data` VALUES ('6', '0', '-1', 'Le cimetiere');
INSERT INTO `subarea_data` VALUES ('7', '0', '-1', 'Les cryptes');
INSERT INTO `subarea_data` VALUES ('8', '0', '-1', 'Campement des Bworks');
INSERT INTO `subarea_data` VALUES ('9', '0', '-1', 'La foret malefique');
INSERT INTO `subarea_data` VALUES ('10', '0', '-1', 'Le village');
INSERT INTO `subarea_data` VALUES ('11', '0', '-1', 'Territoire des Porcos');
INSERT INTO `subarea_data` VALUES ('12', '0', '-1', 'La peninsule des gelees');
INSERT INTO `subarea_data` VALUES ('13', '0', '-1', 'Le temple Feca');
INSERT INTO `subarea_data` VALUES ('14', '0', '-1', 'Le temple Osamodas');
INSERT INTO `subarea_data` VALUES ('15', '0', '-1', 'Le temple Enutrof');
INSERT INTO `subarea_data` VALUES ('16', '0', '-1', 'Le temple Sram');
INSERT INTO `subarea_data` VALUES ('17', '0', '-1', 'Le temple Xelor');
INSERT INTO `subarea_data` VALUES ('18', '0', '-1', 'Le temple Ecaflip');
INSERT INTO `subarea_data` VALUES ('19', '0', '-1', 'Le temple Iop');
INSERT INTO `subarea_data` VALUES ('20', '0', '-1', 'Le temple Cra ');
INSERT INTO `subarea_data` VALUES ('21', '0', '-1', 'Le temple Sadida');
INSERT INTO `subarea_data` VALUES ('22', '0', '-1', 'Bord de la foret malefique');
INSERT INTO `subarea_data` VALUES ('23', '0', '-1', 'La presqu\'Ile des Dragoeufs');
INSERT INTO `subarea_data` VALUES ('25', '1', '-1', 'Sous-terrains des Wabbits');
INSERT INTO `subarea_data` VALUES ('26', '0', '-1', 'Le temple Eniripsa');
INSERT INTO `subarea_data` VALUES ('27', '0', '-1', 'Cote d\'Asse');
INSERT INTO `subarea_data` VALUES ('28', '0', '-1', 'Garnison d\'Amakna');
INSERT INTO `subarea_data` VALUES ('29', '0', '-1', 'Souterrain');
INSERT INTO `subarea_data` VALUES ('30', '4', '-1', 'Le berceau');
INSERT INTO `subarea_data` VALUES ('31', '0', '-1', 'Le marecage');
INSERT INTO `subarea_data` VALUES ('32', '5', '-1', 'Sufokia');
INSERT INTO `subarea_data` VALUES ('33', '6', '-1', 'Foret des Abraknydes');
INSERT INTO `subarea_data` VALUES ('34', '3', '-1', 'Prison');
INSERT INTO `subarea_data` VALUES ('35', '0', '-1', 'Porte de Sufokia');
INSERT INTO `subarea_data` VALUES ('37', '7', '-1', 'Bonta');
INSERT INTO `subarea_data` VALUES ('38', '8', '-1', 'Plaine de Cania');
INSERT INTO `subarea_data` VALUES ('39', '0', '-1', 'Le repaire des Roublards');
INSERT INTO `subarea_data` VALUES ('41', '0', '-1', 'Le temple Sacrieur');
INSERT INTO `subarea_data` VALUES ('42', '8', '-1', 'Route de Bonta');
INSERT INTO `subarea_data` VALUES ('43', '7', '-1', 'Fortification de Bonta');
INSERT INTO `subarea_data` VALUES ('44', '7', '-1', 'Quartier des Boulangers');
INSERT INTO `subarea_data` VALUES ('45', '7', '-1', 'Quartier de la Milice');
INSERT INTO `subarea_data` VALUES ('46', '7', '-1', 'Quartier des Bouchers');
INSERT INTO `subarea_data` VALUES ('47', '7', '-1', 'Quartier des Forgerons');
INSERT INTO `subarea_data` VALUES ('48', '7', '-1', 'Quartier des Bucherons');
INSERT INTO `subarea_data` VALUES ('49', '7', '-1', 'Quartier des Bricoleurs');
INSERT INTO `subarea_data` VALUES ('50', '7', '-1', 'Quartier des Tailleurs');
INSERT INTO `subarea_data` VALUES ('51', '7', '-1', 'Quartier des Bijoutiers');
INSERT INTO `subarea_data` VALUES ('53', '11', '-1', 'Brakmar');
INSERT INTO `subarea_data` VALUES ('54', '8', '-1', 'Massif de Cania');
INSERT INTO `subarea_data` VALUES ('55', '8', '-1', 'Penates du Corbac');
INSERT INTO `subarea_data` VALUES ('56', '8', '-1', 'Foret de Cania');
INSERT INTO `subarea_data` VALUES ('57', '12', '-1', 'Lande de Sidimote');
INSERT INTO `subarea_data` VALUES ('59', '8', '-1', 'Cimetiere de Bonta');
INSERT INTO `subarea_data` VALUES ('61', '12', '-1', 'Cimetiere des Tortures');
INSERT INTO `subarea_data` VALUES ('62', '13', '-1', 'Village Dopeul');
INSERT INTO `subarea_data` VALUES ('63', '13', '-1', 'Prisme des Dopeuls');
INSERT INTO `subarea_data` VALUES ('64', '13', '-1', 'Premiere salle du prisme');
INSERT INTO `subarea_data` VALUES ('65', '13', '-1', 'Seconde salle du prisme');
INSERT INTO `subarea_data` VALUES ('66', '13', '-1', 'Troisieme salle du prisme');
INSERT INTO `subarea_data` VALUES ('67', '13', '-1', 'Quatrieme salle du prisme');
INSERT INTO `subarea_data` VALUES ('68', '8', '-1', 'Les Champs de Cania');
INSERT INTO `subarea_data` VALUES ('69', '8', '-1', 'Bois de Litneg');
INSERT INTO `subarea_data` VALUES ('70', '8', '-1', 'Plaines Rocheuses');
INSERT INTO `subarea_data` VALUES ('71', '12', '-1', 'Gisgoul, le village devaste ');
INSERT INTO `subarea_data` VALUES ('72', '12', '-1', 'Facade de Brakmar');
INSERT INTO `subarea_data` VALUES ('73', '7', '-1', 'Egout de Bonta');
INSERT INTO `subarea_data` VALUES ('74', '13', '-1', 'Entrainement Dopeuls');
INSERT INTO `subarea_data` VALUES ('75', '11', '-1', 'Egout de Brakmar');
INSERT INTO `subarea_data` VALUES ('76', '14', '-1', 'Village Brigandins');
INSERT INTO `subarea_data` VALUES ('77', '0', '-1', 'La gelaxieme dimension');
INSERT INTO `subarea_data` VALUES ('78', '0', '-1', 'La gelaxieme dimension (royale)');
INSERT INTO `subarea_data` VALUES ('79', '14', '-1', 'Premiere plate-forme');
INSERT INTO `subarea_data` VALUES ('80', '14', '-1', 'Seconde plate-forme');
INSERT INTO `subarea_data` VALUES ('81', '14', '-1', 'Prisme Brigandin');
INSERT INTO `subarea_data` VALUES ('82', '4', '-1', 'Donjon des Bouftous');
INSERT INTO `subarea_data` VALUES ('83', '17', '-1', 'Tutorial');
INSERT INTO `subarea_data` VALUES ('84', '15', '-1', 'Foire du Trool');
INSERT INTO `subarea_data` VALUES ('85', '16', '-1', 'Jeu du Bouftou');
INSERT INTO `subarea_data` VALUES ('86', '15', '-1', 'Gladiatrool');
INSERT INTO `subarea_data` VALUES ('87', '0', '-1', 'Amakna Sud');
INSERT INTO `subarea_data` VALUES ('88', '17', '-1', 'Tainela');
INSERT INTO `subarea_data` VALUES ('89', '0', '-1', 'Tournoi Monde du Jeu');
INSERT INTO `subarea_data` VALUES ('91', '0', '-1', 'Souterrain mysterieux');
INSERT INTO `subarea_data` VALUES ('92', '18', '-1', 'Contour d\'Astrub');
INSERT INTO `subarea_data` VALUES ('93', '2', '-1', 'La plage de Moon');
INSERT INTO `subarea_data` VALUES ('94', '12', '-1', 'Donjon du Bworker');
INSERT INTO `subarea_data` VALUES ('95', '18', '-1', 'Cite d\'Astrub');
INSERT INTO `subarea_data` VALUES ('96', '18', '-1', 'Exploitation miniere d\'Astrub');
INSERT INTO `subarea_data` VALUES ('97', '18', '-1', 'Foret d\'Astrub');
INSERT INTO `subarea_data` VALUES ('98', '18', '-1', 'Champs d\'Astrub');
INSERT INTO `subarea_data` VALUES ('99', '18', '-1', 'Souterrain d\'Astrub');
INSERT INTO `subarea_data` VALUES ('100', '18', '-1', 'Souterrain profond d\'Astrub');
INSERT INTO `subarea_data` VALUES ('101', '18', '-1', 'Le coin des Tofus');
INSERT INTO `subarea_data` VALUES ('102', '25', '-1', 'Le champ du repos');
INSERT INTO `subarea_data` VALUES ('103', '0', '-1', 'Territoire des Bandits');
INSERT INTO `subarea_data` VALUES ('105', '19', '-1', 'Pandala Neutre');
INSERT INTO `subarea_data` VALUES ('106', '20', '-1', 'Bordure d\'Akwadala');
INSERT INTO `subarea_data` VALUES ('107', '22', '-1', 'Bordure de Feudala');
INSERT INTO `subarea_data` VALUES ('108', '23', '-1', 'Bordure d\'Aerdala');
INSERT INTO `subarea_data` VALUES ('109', '21', '-1', 'Bordure de Terrdala');
INSERT INTO `subarea_data` VALUES ('110', '0', '-1', 'Amakna passe ');
INSERT INTO `subarea_data` VALUES ('111', '23', '-1', 'Porte Aerdala');
INSERT INTO `subarea_data` VALUES ('112', '22', '-1', 'Porte Feudala');
INSERT INTO `subarea_data` VALUES ('113', '20', '-1', 'Porte Akwadala');
INSERT INTO `subarea_data` VALUES ('114', '21', '-1', 'Porte Terrdala');
INSERT INTO `subarea_data` VALUES ('115', '23', '-1', 'Village d\'Aerdala');
INSERT INTO `subarea_data` VALUES ('116', '22', '-1', 'Village de Feudala');
INSERT INTO `subarea_data` VALUES ('117', '20', '-1', 'Village d\'Akwadala');
INSERT INTO `subarea_data` VALUES ('118', '21', '-1', 'Village de Terrdala');
INSERT INTO `subarea_data` VALUES ('119', '19', '-1', 'Village de Pandala');
INSERT INTO `subarea_data` VALUES ('120', '23', '-1', 'Prisme Aerdala');
INSERT INTO `subarea_data` VALUES ('121', '22', '-1', 'Prisme Feudala');
INSERT INTO `subarea_data` VALUES ('122', '20', '-1', 'Prisme Akwadala');
INSERT INTO `subarea_data` VALUES ('123', '21', '-1', 'Prisme Terrdala');
INSERT INTO `subarea_data` VALUES ('124', '24', '-1', 'Caverne des Bulbes');
INSERT INTO `subarea_data` VALUES ('125', '24', '-1', 'Repaire des Pandikazes - Premiere plate-forme');
INSERT INTO `subarea_data` VALUES ('126', '24', '-1', 'Repaire des Pandikazes - Seconde plate-forme');
INSERT INTO `subarea_data` VALUES ('127', '24', '-1', 'Repaire des Pandikazes - Troisieme plate-forme');
INSERT INTO `subarea_data` VALUES ('128', '24', '-1', 'Repaire des Pandikazes - Quatrieme plate-forme');
INSERT INTO `subarea_data` VALUES ('129', '24', '-1', 'Repaire des Pandikazes - Cinquieme plate-forme');
INSERT INTO `subarea_data` VALUES ('130', '24', '-1', 'Repaire des Pandikazes - Sixieme plate-forme');
INSERT INTO `subarea_data` VALUES ('131', '24', '-1', 'Repaire des Pandikazes - Septieme plate-forme');
INSERT INTO `subarea_data` VALUES ('132', '24', '-1', 'Repaire des Pandikazes - Huitieme plate-forme');
INSERT INTO `subarea_data` VALUES ('133', '24', '-1', 'Donjon des Kitsounes - Salle 1');
INSERT INTO `subarea_data` VALUES ('134', '24', '-1', 'Donjon des Kitsounes - Salle 2');
INSERT INTO `subarea_data` VALUES ('135', '24', '-1', 'Donjon des Kitsounes - Salle 3');
INSERT INTO `subarea_data` VALUES ('136', '24', '-1', 'Donjon des Kitsounes - Salle 4');
INSERT INTO `subarea_data` VALUES ('137', '24', '-1', 'Donjon des Kitsounes - Salle 4');
INSERT INTO `subarea_data` VALUES ('138', '24', '-1', 'Donjon des Kitsounes - Salle 4');
INSERT INTO `subarea_data` VALUES ('139', '24', '-1', 'Donjon des Kitsounes - Salle 5');
INSERT INTO `subarea_data` VALUES ('140', '24', '-1', 'Donjon des Kitsounes - Salle 6');
INSERT INTO `subarea_data` VALUES ('141', '24', '-1', 'Donjon des Kitsounes - Repaire du Tanukoui');
INSERT INTO `subarea_data` VALUES ('143', '19', '-1', 'Pont de Pandala');
INSERT INTO `subarea_data` VALUES ('144', '24', '-1', 'Donjon des Firefoux');
INSERT INTO `subarea_data` VALUES ('145', '24', '-1', 'Donjon des Firefoux - Salle 1');
INSERT INTO `subarea_data` VALUES ('146', '24', '-1', 'Donjon des Firefoux - Salle 2');
INSERT INTO `subarea_data` VALUES ('147', '24', '-1', 'Donjon des Firefoux - Salle 3');
INSERT INTO `subarea_data` VALUES ('148', '24', '-1', 'Donjon des Firefoux - Salle 4');
INSERT INTO `subarea_data` VALUES ('149', '24', '-1', 'Donjon des Firefoux - Salle 5');
INSERT INTO `subarea_data` VALUES ('150', '24', '-1', 'Donjon des Firefoux - Salle 6');
INSERT INTO `subarea_data` VALUES ('151', '24', '-1', 'Donjon des Firefoux - Salle 7');
INSERT INTO `subarea_data` VALUES ('152', '19', '-1', 'L\'Ile de Grobe');
INSERT INTO `subarea_data` VALUES ('153', '24', '-1', 'Repaire des Pandikazes - Plate-forme finale');
INSERT INTO `subarea_data` VALUES ('154', '43', '-1', 'Donjon Cochon - Salle 1');
INSERT INTO `subarea_data` VALUES ('155', '43', '-1', 'Donjon Cochon - Salle 2');
INSERT INTO `subarea_data` VALUES ('156', '43', '-1', 'Donjon Cochon - Salle 3');
INSERT INTO `subarea_data` VALUES ('157', '43', '-1', 'Donjon Cochon - Salle 4');
INSERT INTO `subarea_data` VALUES ('158', '43', '-1', 'Donjon Cochon - Salle 5');
INSERT INTO `subarea_data` VALUES ('159', '43', '-1', 'Donjon Cochon - Salle 6');
INSERT INTO `subarea_data` VALUES ('161', '1', '-1', 'Ile des Wabbits');
INSERT INTO `subarea_data` VALUES ('162', '1', '-1', 'Ilot des Wabbits');
INSERT INTO `subarea_data` VALUES ('163', '1', '-1', 'Ile des Wabbits Squelettes');
INSERT INTO `subarea_data` VALUES ('164', '1', '-1', 'Ile du chateau des Wabbits');
INSERT INTO `subarea_data` VALUES ('165', '2', '-1', 'La jungle profonde de Moon');
INSERT INTO `subarea_data` VALUES ('166', '2', '-1', 'Le chemin vers Moon');
INSERT INTO `subarea_data` VALUES ('167', '2', '-1', 'Le bateau pirate');
INSERT INTO `subarea_data` VALUES ('168', '6', '-1', 'Foret des Abraknydes Sombres');
INSERT INTO `subarea_data` VALUES ('169', '6', '-1', 'Oree de la foret des Abraknydes');
INSERT INTO `subarea_data` VALUES ('170', '0', '-1', 'Plaine des Scarafeuilles');
INSERT INTO `subarea_data` VALUES ('171', '19', '-1', 'Foret de Pandala');
INSERT INTO `subarea_data` VALUES ('173', '18', '-1', 'Prairies d\'Astrub');
INSERT INTO `subarea_data` VALUES ('174', '18', '-1', 'Campement des Bandits Manchots');
INSERT INTO `subarea_data` VALUES ('175', '27', '-1', 'Donjon Abraknyde - Salle 1');
INSERT INTO `subarea_data` VALUES ('177', '8', '-1', 'Prairie des Blops');
INSERT INTO `subarea_data` VALUES ('178', '8', '-1', 'Plaine des Porkass');
INSERT INTO `subarea_data` VALUES ('179', '0', '-1', 'Le coin des Boos');
INSERT INTO `subarea_data` VALUES ('180', '0', '-1', 'Le chateau d\'Amakna');
INSERT INTO `subarea_data` VALUES ('181', '0', '-1', 'Souterrain du Chateau d\'Amakna');
INSERT INTO `subarea_data` VALUES ('182', '28', '-1', 'Village des Eleveurs');
INSERT INTO `subarea_data` VALUES ('200', '26', '-1', 'Labyrinthe du Dragon Cochon');
INSERT INTO `subarea_data` VALUES ('201', '29', '-1', 'Donjon des Tofus - Salle 1');
INSERT INTO `subarea_data` VALUES ('202', '29', '-1', 'Donjon des Tofus - Salle 2');
INSERT INTO `subarea_data` VALUES ('203', '29', '-1', 'Donjon des Tofus - Salle 3');
INSERT INTO `subarea_data` VALUES ('204', '29', '-1', 'Donjon des Tofus - Salle 4');
INSERT INTO `subarea_data` VALUES ('205', '29', '-1', 'Donjon des Tofus - Salle 5');
INSERT INTO `subarea_data` VALUES ('206', '29', '-1', 'Donjon des Tofus - Salle 6');
INSERT INTO `subarea_data` VALUES ('207', '29', '-1', 'Donjon des Tofus - Salle 7');
INSERT INTO `subarea_data` VALUES ('208', '29', '-1', 'Donjon des Tofus - Salle 8');
INSERT INTO `subarea_data` VALUES ('209', '30', '-1', 'L\'Ile du Minotoror');
INSERT INTO `subarea_data` VALUES ('210', '31', '-1', 'Le labyrinthe du Minotoror');
INSERT INTO `subarea_data` VALUES ('211', '32', '-1', 'La bibliotheque du MaItre Corbac');
INSERT INTO `subarea_data` VALUES ('212', '33', '-1', 'Donjon des Canides - Entree');
INSERT INTO `subarea_data` VALUES ('213', '33', '-1', 'Donjon des Canides - Salle 1');
INSERT INTO `subarea_data` VALUES ('214', '33', '-1', 'Donjon des Canides - Salle 2');
INSERT INTO `subarea_data` VALUES ('215', '33', '-1', 'Donjon des Canides - Salle 3');
INSERT INTO `subarea_data` VALUES ('216', '33', '-1', 'Donjon des Canides - Salle 4');
INSERT INTO `subarea_data` VALUES ('217', '33', '-1', 'Donjon des Canides - Salle 5');
INSERT INTO `subarea_data` VALUES ('218', '33', '-1', 'Donjon des Canides - Salle 6');
INSERT INTO `subarea_data` VALUES ('219', '33', '-1', 'Donjon des Canides - Salle 7');
INSERT INTO `subarea_data` VALUES ('220', '33', '-1', 'Donjon des Canides - Salle 8');
INSERT INTO `subarea_data` VALUES ('221', '33', '-1', 'Donjon des Canides - Salle 9');
INSERT INTO `subarea_data` VALUES ('222', '33', '-1', 'Donjon des Canides - Salle 10');
INSERT INTO `subarea_data` VALUES ('223', '34', '-1', 'Caverne du Koulosse - Salle 1');
INSERT INTO `subarea_data` VALUES ('224', '34', '-1', 'Caverne du Koulosse - Salle 2');
INSERT INTO `subarea_data` VALUES ('225', '34', '-1', 'Caverne du Koulosse - Salle 3');
INSERT INTO `subarea_data` VALUES ('226', '34', '-1', 'Caverne du Koulosse - Salle 4');
INSERT INTO `subarea_data` VALUES ('227', '34', '-1', 'Caverne du Koulosse - Salle 5');
INSERT INTO `subarea_data` VALUES ('228', '34', '-1', 'Caverne du Koulosse - Salle 6');
INSERT INTO `subarea_data` VALUES ('229', '34', '-1', 'Caverne du Koulosse - L\'antre');
INSERT INTO `subarea_data` VALUES ('230', '28', '-1', 'Cimetiere primitif');
INSERT INTO `subarea_data` VALUES ('231', '28', '-1', 'Lacs enchantes');
INSERT INTO `subarea_data` VALUES ('232', '28', '-1', 'Marecages nauseabonds');
INSERT INTO `subarea_data` VALUES ('233', '28', '-1', 'Marecages sans fond');
INSERT INTO `subarea_data` VALUES ('234', '28', '-1', 'Foret de Kaliptus');
INSERT INTO `subarea_data` VALUES ('235', '28', '-1', 'Territoire des Dragodindes Sauvages');
INSERT INTO `subarea_data` VALUES ('236', '36', '-1', 'Sanctuaire des Familiers');
INSERT INTO `subarea_data` VALUES ('243', '37', '-1', 'Donjon des Craqueleurs - Salle 1');
INSERT INTO `subarea_data` VALUES ('244', '37', '-1', 'Donjon des Craqueleurs - Salle 2');
INSERT INTO `subarea_data` VALUES ('245', '37', '-1', 'Donjon des Craqueleurs - Salle 3');
INSERT INTO `subarea_data` VALUES ('246', '37', '-1', 'Donjon des Craqueleurs - Salle 4');
INSERT INTO `subarea_data` VALUES ('247', '37', '-1', 'Donjon des Craqueleurs - Salle 5');
INSERT INTO `subarea_data` VALUES ('248', '37', '-1', 'Donjon des Craqueleurs - Salle 6');
INSERT INTO `subarea_data` VALUES ('249', '37', '-1', 'Donjon des Craqueleurs - Salle 7');
INSERT INTO `subarea_data` VALUES ('250', '37', '-1', 'Donjon des Craqueleurs - Salle 8');
INSERT INTO `subarea_data` VALUES ('251', '37', '-1', 'Donjon des Craqueleurs - Salle 10');
INSERT INTO `subarea_data` VALUES ('252', '37', '-1', 'Donjon des Craqueleurs - Salle 11');
INSERT INTO `subarea_data` VALUES ('253', '28', '-1', 'Canyon sauvage');
INSERT INTO `subarea_data` VALUES ('254', '35', '-1', 'Repaire de Skeunk - Salle 1');
INSERT INTO `subarea_data` VALUES ('255', '35', '-1', 'Repaire de Skeunk - Salle 2');
INSERT INTO `subarea_data` VALUES ('256', '35', '-1', 'Repaire de Skeunk - Salle 3');
INSERT INTO `subarea_data` VALUES ('257', '35', '-1', 'Repaire de Skeunk - Emeraude');
INSERT INTO `subarea_data` VALUES ('258', '35', '-1', 'Repaire de Skeunk - Rubise');
INSERT INTO `subarea_data` VALUES ('259', '35', '-1', 'Repaire de Skeunk - Saphira');
INSERT INTO `subarea_data` VALUES ('260', '35', '-1', 'Repaire de Skeunk - Diamantine');
INSERT INTO `subarea_data` VALUES ('261', '35', '-1', 'Repaire de Skeunk - Antre');
INSERT INTO `subarea_data` VALUES ('266', '35', '-1', 'Repaire de Skeunk - Salle 4');
INSERT INTO `subarea_data` VALUES ('267', '35', '-1', 'Repaire de Skeunk - Salle 5');
INSERT INTO `subarea_data` VALUES ('268', '29', '-1', 'Donjon des Tofus - Salle 9');
INSERT INTO `subarea_data` VALUES ('269', '29', '-1', 'Donjon des Tofus - Salle 10');
INSERT INTO `subarea_data` VALUES ('270', '29', '-1', 'Donjon des Tofus - Salle 11');
INSERT INTO `subarea_data` VALUES ('271', '29', '-1', 'Donjon des Tofus - Salle 12');
INSERT INTO `subarea_data` VALUES ('272', '29', '-1', 'Donjon des Tofus - Salle 13');
INSERT INTO `subarea_data` VALUES ('273', '29', '-1', 'Donjon des Tofus - Salle 14');
INSERT INTO `subarea_data` VALUES ('274', '29', '-1', 'Donjon des Tofus - Salle 15');
INSERT INTO `subarea_data` VALUES ('275', '28', '-1', 'Vallee de la Morh\'Kitu');
INSERT INTO `subarea_data` VALUES ('276', '0', '-1', 'Campement des Gobelins');
INSERT INTO `subarea_data` VALUES ('277', '0', '-1', 'Village des Bworks');
INSERT INTO `subarea_data` VALUES ('278', '18', '-1', 'Elevage de Bouftous du Chateau d\'Amakna');
INSERT INTO `subarea_data` VALUES ('279', '7', '-1', 'Bordure de Bonta');
INSERT INTO `subarea_data` VALUES ('280', '11', '-1', 'Bordure de Brakmar');
INSERT INTO `subarea_data` VALUES ('284', '39', '-1', 'Donjon des Bworks - Salle 1');
INSERT INTO `subarea_data` VALUES ('285', '39', '-1', 'Donjon des Bworks - Salle 2');
INSERT INTO `subarea_data` VALUES ('286', '39', '-1', 'Donjon des Bworks - Salle 3');
INSERT INTO `subarea_data` VALUES ('287', '39', '-1', 'Donjon des Bworks - Cachot');
INSERT INTO `subarea_data` VALUES ('288', '39', '-1', 'Donjon des Bworks - Salle 4');
INSERT INTO `subarea_data` VALUES ('289', '39', '-1', 'Donjon des Bworks - Salle 5');
INSERT INTO `subarea_data` VALUES ('290', '39', '-1', 'Donjon des Bworks - Salle 6');
INSERT INTO `subarea_data` VALUES ('291', '39', '-1', 'Donjon des Bworks - Salle 7');
INSERT INTO `subarea_data` VALUES ('292', '33', '-1', 'Donjon des Canides - Salle 11');
INSERT INTO `subarea_data` VALUES ('293', '33', '-1', 'Donjon des Canides - Salle 12');
INSERT INTO `subarea_data` VALUES ('294', '33', '-1', 'Donjon des Canides - Salle 13');
INSERT INTO `subarea_data` VALUES ('295', '33', '-1', 'Donjon des Canides - Salle 14');
INSERT INTO `subarea_data` VALUES ('296', '33', '-1', 'Donjon des Canides - Salle 15');
INSERT INTO `subarea_data` VALUES ('297', '40', '-1', 'Donjon des Scarafeuilles - Salle 1');
INSERT INTO `subarea_data` VALUES ('298', '40', '-1', 'Donjon des Scarafeuilles - Salle 2');
INSERT INTO `subarea_data` VALUES ('299', '40', '-1', 'Donjon des Scarafeuilles - Salle 3');
INSERT INTO `subarea_data` VALUES ('300', '40', '-1', 'Donjon des Scarafeuilles - Salle 4');
INSERT INTO `subarea_data` VALUES ('301', '40', '-1', 'Donjon des Scarafeuilles - Salle 5');
INSERT INTO `subarea_data` VALUES ('302', '40', '-1', 'Donjon des Scarafeuilles - Salle 6');
INSERT INTO `subarea_data` VALUES ('303', '40', '-1', 'Donjon des Scarafeuilles - Salle 7');
INSERT INTO `subarea_data` VALUES ('304', '40', '-1', 'Donjon des Scarafeuilles - Salle 8');
INSERT INTO `subarea_data` VALUES ('306', '41', '-1', 'Donjon des Champs - Salle 1');
INSERT INTO `subarea_data` VALUES ('307', '41', '-1', 'Donjon des Champs - Salle 2');
INSERT INTO `subarea_data` VALUES ('308', '41', '-1', 'Donjon des Champs - Salle 3');
INSERT INTO `subarea_data` VALUES ('309', '41', '-1', 'Donjon des Champs - Salle 4');
INSERT INTO `subarea_data` VALUES ('310', '41', '-1', 'Donjon des Champs - Salle 5');
INSERT INTO `subarea_data` VALUES ('311', '41', '-1', 'Donjon des Champs - Salle 6');
INSERT INTO `subarea_data` VALUES ('312', '41', '-1', 'Donjon des Champs - Salle 7');
INSERT INTO `subarea_data` VALUES ('313', '29', '-1', 'Donjon des Tofus - Salle 16');
INSERT INTO `subarea_data` VALUES ('314', '0', '-1', 'Sanctuaire des Dragoeufs');
INSERT INTO `subarea_data` VALUES ('315', '0', '-1', 'Village des Dragoeufs');
INSERT INTO `subarea_data` VALUES ('316', '0', '-1', 'Sous terrain des Dragoeufs');
INSERT INTO `subarea_data` VALUES ('317', '37', '-1', 'Donjon des Craqueleurs - Salle 9');
INSERT INTO `subarea_data` VALUES ('318', '18', '-1', 'Alkatraz');
INSERT INTO `subarea_data` VALUES ('319', '31', '-1', 'Le labyrinthe du Minotoror');
INSERT INTO `subarea_data` VALUES ('320', '42', '-1', 'L\'Ile de Nowel');
INSERT INTO `subarea_data` VALUES ('321', '42', '-1', 'Le donjon de Nowel');
INSERT INTO `subarea_data` VALUES ('322', '43', '-1', 'Donjon Cochon - Salle 7');
INSERT INTO `subarea_data` VALUES ('323', '43', '-1', 'Donjon Cochon - Salle 8');
INSERT INTO `subarea_data` VALUES ('324', '43', '-1', 'Donjon Cochon - Salle 9');
INSERT INTO `subarea_data` VALUES ('325', '44', '-1', 'Donjon Dragoeuf - Salle 1');
INSERT INTO `subarea_data` VALUES ('326', '44', '-1', 'Donjon Dragoeuf - Salle 2');
INSERT INTO `subarea_data` VALUES ('327', '44', '-1', 'Donjon Dragoeuf - Salle 3');
INSERT INTO `subarea_data` VALUES ('328', '44', '-1', 'Donjon Dragoeuf - Salle 4');
INSERT INTO `subarea_data` VALUES ('329', '44', '-1', 'Donjon Dragoeuf - Salle 5');
INSERT INTO `subarea_data` VALUES ('330', '44', '-1', 'Donjon Dragoeuf - Salle 6');
INSERT INTO `subarea_data` VALUES ('331', '44', '-1', 'Donjon Dragoeuf - Salle 7');
INSERT INTO `subarea_data` VALUES ('332', '44', '-1', 'Donjon Dragoeuf - Salle 8');
INSERT INTO `subarea_data` VALUES ('333', '44', '-1', 'Donjon Dragoeuf - Salle 9');
INSERT INTO `subarea_data` VALUES ('334', '8', '-1', 'Baie de Cania');
INSERT INTO `subarea_data` VALUES ('335', '18', '-1', 'Calanques d\'Astrub');
INSERT INTO `subarea_data` VALUES ('336', '18', '-1', 'Donjon Ensable ');
INSERT INTO `subarea_data` VALUES ('337', '7', '-1', 'Donjon des Rats de Bonta');
INSERT INTO `subarea_data` VALUES ('338', '11', '-1', 'Donjon des Rats de Brakmar');
INSERT INTO `subarea_data` VALUES ('339', '0', '-1', 'Donjon des Rats du Chateau d\'Amakna');
INSERT INTO `subarea_data` VALUES ('440', '45', '-1', 'Pitons rocheux');
INSERT INTO `subarea_data` VALUES ('441', '45', '-1', 'Clairiere');
INSERT INTO `subarea_data` VALUES ('442', '45', '-1', 'Lac');
INSERT INTO `subarea_data` VALUES ('443', '45', '-1', 'Foret');
INSERT INTO `subarea_data` VALUES ('444', '45', '-1', 'Champs');
INSERT INTO `subarea_data` VALUES ('445', '45', '-1', 'Prairie');
INSERT INTO `subarea_data` VALUES ('446', '45', '-1', 'Temple');
INSERT INTO `subarea_data` VALUES ('447', '45', '-1', 'Donjon');
INSERT INTO `subarea_data` VALUES ('448', '45', '-1', 'Divers');
INSERT INTO `subarea_data` VALUES ('449', '45', '-1', 'Cimetiere');
INSERT INTO `subarea_data` VALUES ('450', '45', '-1', 'Sortie du temple');
INSERT INTO `subarea_data` VALUES ('451', '46', '-1', 'Ile des naufrages');
INSERT INTO `subarea_data` VALUES ('452', '46', '-1', 'Mer');
INSERT INTO `subarea_data` VALUES ('453', '46', '-1', 'Plage de Corail');
INSERT INTO `subarea_data` VALUES ('454', '46', '-1', 'Plaines herbeuses');
INSERT INTO `subarea_data` VALUES ('455', '46', '-1', 'Jungle obscure');
INSERT INTO `subarea_data` VALUES ('457', '46', '-1', 'Tourbiere sans fond');
INSERT INTO `subarea_data` VALUES ('459', '46', '-1', 'Canopee du Kimbo');
INSERT INTO `subarea_data` VALUES ('460', '46', '-1', 'Grotte Hesque');
INSERT INTO `subarea_data` VALUES ('461', '46', '-1', 'L\'arche d\'Otomai');
INSERT INTO `subarea_data` VALUES ('462', '46', '-1', 'La clairiere de Floribonde');
INSERT INTO `subarea_data` VALUES ('463', '46', '-1', 'Le laboratoire du Tynril');
INSERT INTO `subarea_data` VALUES ('464', '46', '-1', 'Tronc de l\'arbre Hakam');
INSERT INTO `subarea_data` VALUES ('465', '46', '-1', 'Le village des eleveurs');
INSERT INTO `subarea_data` VALUES ('466', '46', '-1', 'Le village cotier');
INSERT INTO `subarea_data` VALUES ('467', '46', '-1', 'Cimetiere de l\'Ile d\'Otomai');
INSERT INTO `subarea_data` VALUES ('468', '47', '-1', 'Village des Zoths');
INSERT INTO `subarea_data` VALUES ('469', '46', '-1', 'Village de la Canopee');
INSERT INTO `subarea_data` VALUES ('470', '46', '-1', 'Goulet du Rasboul');
INSERT INTO `subarea_data` VALUES ('471', '46', '-1', 'Tourbiere nauseabonde');
INSERT INTO `subarea_data` VALUES ('472', '46', '-1', 'Feuillage de L\'arbre Hakam');
INSERT INTO `subarea_data` VALUES ('473', '46', '-1', 'Le laboratoire cache ');
INSERT INTO `subarea_data` VALUES ('474', '46', '-1', 'Cale de l\'arche d\'Otomai');
INSERT INTO `subarea_data` VALUES ('476', '19', '-1', 'Pont de Grobe');
INSERT INTO `subarea_data` VALUES ('477', '47', '-1', 'Prisme Zothier');
INSERT INTO `subarea_data` VALUES ('478', '47', '-1', 'Gardiens de la porte des Zoths');
INSERT INTO `subarea_data` VALUES ('479', '0', '-1', 'Riviere Kawaii');
INSERT INTO `subarea_data` VALUES ('480', '0', '-1', 'Montagne basse des Craqueleurs');
INSERT INTO `subarea_data` VALUES ('481', '0', '-1', 'Clairiere de Brouce Boulgour');
INSERT INTO `subarea_data` VALUES ('482', '0', '-1', 'La Millifutaie ');
INSERT INTO `subarea_data` VALUES ('483', '0', '-1', 'Le chemin de fer abandonne ');
INSERT INTO `subarea_data` VALUES ('484', '0', '-1', 'Oree de la Millifutaie');
INSERT INTO `subarea_data` VALUES ('485', '0', '-1', 'La campagne');
INSERT INTO `subarea_data` VALUES ('486', '0', '-1', 'Le Bosquet du petit talus');
INSERT INTO `subarea_data` VALUES ('487', '19', '-1', 'Grenier-Cachot de Pandala Air');
INSERT INTO `subarea_data` VALUES ('488', '0', '-1', 'Souterrains d\'Amakna');
INSERT INTO `subarea_data` VALUES ('490', '0', '-1', 'Rivage du golfe sufokien');
INSERT INTO `subarea_data` VALUES ('491', '0', '-1', 'Donjon des Larves');
INSERT INTO `subarea_data` VALUES ('492', '0', '-1', 'Passage vers Brakmar');
INSERT INTO `subarea_data` VALUES ('493', '8', '-1', 'Donjon des Blops');
INSERT INTO `subarea_data` VALUES ('494', '12', '-1', 'Donjon Fungus');
INSERT INTO `subarea_data` VALUES ('495', '12', '-1', 'Caverne des Fungus');
INSERT INTO `subarea_data` VALUES ('496', '12', '-1', 'Donjon de Ku\'tan');
INSERT INTO `subarea_data` VALUES ('497', '8', '-1', 'Donjon d\'Ilyzaelle');
INSERT INTO `subarea_data` VALUES ('498', '8', '-1', 'Sanctuaire Hotomani');
INSERT INTO `subarea_data` VALUES ('499', '30', '-1', 'Cimetiere de l\'Ile du Minotoror');
INSERT INTO `subarea_data` VALUES ('500', '47', '-1', 'Cimetiere du village des Zoths.');
INSERT INTO `subarea_data` VALUES ('501', '0', '-1', 'L\'Ilot Estitch');
INSERT INTO `subarea_data` VALUES ('502', '11', '-1', 'Quartier des bucherons');
INSERT INTO `subarea_data` VALUES ('503', '11', '-1', 'Quartier des bouchers');
INSERT INTO `subarea_data` VALUES ('504', '11', '-1', 'Quartier de la milice');
INSERT INTO `subarea_data` VALUES ('505', '11', '-1', 'Quartier des boulangers');
INSERT INTO `subarea_data` VALUES ('506', '11', '-1', 'Quartier des bijoutiers');
INSERT INTO `subarea_data` VALUES ('507', '11', '-1', 'Quartier des tailleurs');
INSERT INTO `subarea_data` VALUES ('508', '11', '-1', 'Quartier des forgerons');
INSERT INTO `subarea_data` VALUES ('509', '11', '-1', 'Quartier des bricoleurs');
INSERT INTO `subarea_data` VALUES ('510', '11', '-1', 'Arene');
INSERT INTO `subarea_data` VALUES ('511', '11', '-1', 'Centre-ville');
INSERT INTO `subarea_data` VALUES ('512', '7', '-1', 'Arene');
INSERT INTO `subarea_data` VALUES ('513', '7', '-1', 'Centre-ville');
INSERT INTO `subarea_data` VALUES ('514', '7', '-1', 'Tour des ordres');
INSERT INTO `subarea_data` VALUES ('515', '11', '-1', 'Tour des ordres');
INSERT INTO `subarea_data` VALUES ('536', '0', '-1', 'Goultarminator');
